language: java
jdk: oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)